name: CI
on:
  pull_request:
    branches: ["main"]

jobs:
  flutter_test:
    name: Run flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: acctions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Create ios build
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --no-codesign

  build_android:
    name: Create ios build
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
